name: Deploy Backend (Prod)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  deploy-backend-prd:
    runs-on: [self-hosted, Windows, X64, prod]

    steps:
      # 1. 현재 소스 백업
      - name: Backup current source files
        shell: pwsh
        run: |
          $baseDir = 'D:\actions_work\netcore'
          $sourceDir = "$baseDir\source\backend"
          $backupBaseDir = "$baseDir\backup\source\backend"
          $currentMonthDir = Join-Path -Path $backupBaseDir -ChildPath (Get-Date -Format 'yyyyMM')
          $currentDateTime = "$(Get-Date -Format 'yyyyMMdd-HHmmss').zip"

          if (!(Test-Path -Path $currentMonthDir)) {
            New-Item -ItemType Directory -Path $currentMonthDir -Force
          }

          $backupFile = Join-Path -Path $currentMonthDir -ChildPath $currentDateTime
          Compress-Archive -Path "$sourceDir\*" -DestinationPath $backupFile -Force
          Write-Host "✅ Current source files have been backed up to: $backupFile"

      # 2. 현재 배포 파일 백업
      - name: Backup current deploy files
        shell: pwsh
        run: |
          $baseDir = 'D:\actions_work\netcore'
          $deployDir = "$baseDir\deploy\backend"
          $backupBaseDir = "$baseDir\backup\deploy\backend"
          $currentMonthDir = Join-Path -Path $backupBaseDir -ChildPath (Get-Date -Format 'yyyyMM')
          $currentDateTime = "$(Get-Date -Format 'yyyyMMdd-HHmmss').zip"

          if (!(Test-Path -Path $currentMonthDir)) {
            New-Item -ItemType Directory -Path $currentMonthDir -Force
          }

          $backupFile = Join-Path -Path $currentMonthDir -ChildPath $currentDateTime
          Compress-Archive -Path "$deployDir\*" -DestinationPath $backupFile -Force
          Write-Host "✅ Deploy files have been backed up to: $backupFile"

      # 3. 최신 소스 코드 가져오기 (Git 명령어 사용)
      - name: Checkout production repository
        shell: pwsh
        run: |
          $repoUrl = 'https://:${{ secrets.GITHUB_TOKEN }}@github.com//.git' # GitHub 리포지토리 URL (인증 포함)
          $branch = 'main'
          $sourceDir = 'D:\actions_work\netcore\source\backend'

          if (!(Test-Path -Path $sourceDir)) {
            New-Item -ItemType Directory -Path $sourceDir -Force
          }

          cd $sourceDir
          git init
          git remote add origin $repoUrl
          git fetch origin $branch --force
          git reset --hard origin/$branch
          Write-Host "✅ Production repository checked out to: $sourceDir"

      # 4. Java 설정 확인
      - name: Verify Java Environment
        shell: pwsh
        run: |
          Write-Host "Checking Java version..."
          java -version
          Write-Host "✅ Java environment verified."

      # 5. 환경 파일(.env.production) 적용
      - name: Apply production .env file
        shell: pwsh
        run: |
          $envFile = "D:\actions_work\netcore\source\backend\.env.production"
          $destinationPath = "D:\actions_work\netcore\source\backend\.env"

          if (Test-Path -Path $envFile) {
            if (Test-Path -Path $destinationPath) {
              Remove-Item -Path $destinationPath -Force -ErrorAction SilentlyContinue
            }
            Copy-Item -Path $envFile -Destination $destinationPath -Force
            Write-Host "✅ .env.production applied as .env file."
          } else {
            Write-Host "⚠️ Warning: .env.production not found. Using default environment configuration."

      # 6. Backend 빌드 작업 실행
      - name: Build backend
        shell: pwsh
        run: |
          $buildDir = "D:\actions_work\netcore\source\backend"
          cd $buildDir
          gradle clean build
          Write-Host "✅ Backend build completed successfully."

      # 7. 빌드 결과물 배포 디렉터리로 복사
      - name: Deploy built JAR
        shell: pwsh
        run: |
          $baseDir = 'D:\actions_work\netcore'
          $sourceDir = "$baseDir\source\backend"
          $deployDir = "$baseDir\deploy\backend"
          $jarFile = "$sourceDir\build\libs\netcore.jar"

          if (!(Test-Path -Path $deployDir)) {
            New-Item -ItemType Directory -Path $deployDir -Force
          }

          # 기존 JAR 삭제
          Remove-Item -Path "$deployDir\netcore.jar" -Force -ErrorAction SilentlyContinue

          # 새 JAR 배포
          Copy-Item -Path $jarFile -Destination "$deployDir\netcore.jar" -Force
          Write-Host "✅ Built JAR deployed to: $deployDir\netcore.jar"

      # 8. Backend 서비스 재시작
      - name: Restart backend service
        shell: pwsh
        run: |
          $jarFile = "D:\actions_work\netcore\deploy\backend\netcore.jar"

          # 기존 Java 프로세스 종료 (특정 JAR만 중지)
          $javaProcesses = Get-Process -Name "java" -ErrorAction SilentlyContinue | Where-Object { $_.Path -eq $jarFile }
          if ($javaProcesses) {
            $javaProcesses | Stop-Process -Force -ErrorAction SilentlyContinue
            Write-Host "✅ Previous instance stopped."
          }

          # 새 JAR 실행
          Start-Process -FilePath "java" -ArgumentList "-jar $jarFile" -NoNewWindow -PassThru
          Write-Host "✅ Backend service restarted with file: $jarFile"