name: Deploy Backend (Prod)
on:
  push:
    branches:
      - main
jobs:
  deploy-backend-prd:
    runs-on: [self-hosted, windows, prod]
    steps:
      - name: Checkout dev backend
        uses: actions/checkout@v4
        with:
          repository: KTNetCoreSolution/backend
          ref: main
          token: ${{ secrets.NETCORE_PROD_APP_TOKEN }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Apply dev .env
        run: |
          Copy-Item -Path "${{ github.workspace }}/.env" -Destination "${{ github.workspace }}/.env" -Force
      - name: Build backend
        run: ./gradlew clean build
        working-directory: ${{ github.workspace }}/source/backend
      - name: Copy JAR to deploy
        run: Copy-Item -Path "${{ github.workspace }}/source/backend/build/libs/netcore.jar" -Destination "${{ github.workspace }}/deploy/backend/netcore.jar" -Force
      - name: Deploy backend
        run: |
          Stop-Process -Name "java" -Force -ErrorAction SilentlyContinue
          Start-Process -FilePath "java" -ArgumentList "-jar ${{ github.workspace }}/deploy/backend/netcore.jar" -WorkingDirectory "${{ github.workspace }}/deploy/backend" -NoNewWindow
      - name: Backup source
        run: |
          $date = Get-Date -Format "yyyyMM"
          $day = Get-Date -Format "yyyyMMdd"
          New-Item -ItemType Directory -Path "${{ github.workspace }}/backup/source/backend/$date" -Force
          Compress-Archive -Path "${{ github.workspace }}/source/backend/*" -DestinationPath "${{ github.workspace }}/backup/source/backend/$date/$day.zip" -Force
      - name: Backup deploy
        run: |
          $date = Get-Date -Format "yyyyMM"
          $day = Get-Date -Format "yyyyMMdd"
          New-Item -ItemType Directory -Path "${{ github.workspace }}/backup/deploy/backend/$date" -Force
          Compress-Archive -Path "${{ github.workspace }}/deploy/backend/*" -DestinationPath "${{ github.workspace }}/backup/deploy/backend/$date/$day.zip" -Force